language: csharp

services:
    - docker

script:
    - docker-compose -f src/Reichinger.Masterarbeit.PK-4-0/docker-compose.yml build
    - docker-compose -f src/Reichinger.Masterarbeit.PK-4-0/docker-compose.yml up
