dist: trusty
sudo: required
services:
    - docker
env:
    # You may want to update this to whatever the latest version is, or keep it
    # the same as your local machines. However, I have only tested it with 1.8.0+.
    # There should be a time in the future when this is not necessary - it is
    # explained in more detail below.
    DOCKER_COMPOSE_VERSION: 1.8.1
    ASPNETCORE_ENVIRONMENT: Travis


before_install:
  # Shutting down postgres to use port 5432 for docker container
  - sudo service postgresql stop

  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update

  # Now we can install the newer docker-engine which is required for the newer
  # docker-composer we will install next. The messy options are to force it to
  # be non-interactive (normally it asks you a bunch of config questions).
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  # Print out the current docker-compose version. Once this reports 1.6+ then we
  # do not need the following steps.
  - docker-compose --version

script:
    - docker-compose -f docker-compose.development.yml build
    - docker-compose up -d
    - docker-compose ps
    - docker exec coreapp dotnet test /src/Reichinger.Masterarbeit.PK-4-0.Test