# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: "2"

services:
    
    database-server:
        container_name: psqldatabase
        image: psqldatabase
        build:
            context: .
            dockerfile: postgresql.dockerfile
        volumes_from:
            - database-data
        ports:
            - "5433:5432"


    application:
        container_name: coreapp
        image: coreapp
        build:
            context: .
            dockerfile: application.development.dockerfile
        ports:
            - "8000:8000"


    database-data:
        image: psqldatabase
        entrypoint: /bin/bash