# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: "2"

services:
    
    database-server:
        container_name: psqldatabase
        image: psqldatabase
        build:
            context: .
            dockerfile: postgresql.dockerfile
        volumes_from:
            - database-data
        ports:
            - "5432:5432"
        networks:
            - core-application-network


    application:
        environment:
            ASPNETCORE_ENVIRONMENT=Development
        container_name: coreapp
        image: coreapp
        build:
            context: .
            dockerfile: application.dockerfile
        ports:
            - "8000:8000"
        networks:
            - core-application-network


    database-data:
        container_name: data_container
        image: psqldatabase
        entrypoint: /bin/bash
        networks:
            - core-application-network


networks:
    core-application-network:
        driver: bridge
