# Run docker-compose build
# Run docker-compose up

version: "2"

services:
    
    database-server:
        container_name: psqldatabase
        image: psqldatabase
        restart: always
        build:
            context: .
            dockerfile: postgresql.dockerfile
        volumes_from:
            - database-data
        ports:
            - "5432:5432"
        networks:
            - core-application-network


    application:
        container_name: coreapp
        image: coreapp
        restart: always
        build:
            context: .
            dockerfile: application.dockerfile
        ports:
            - "8000:8000"
        extra_hosts:
            - "pk.multimedia.hs-augsburg.de pk:127.0.1.1"
        networks:
            - core-application-network
        hostname: pk


    database-data:
        container_name: data_container
        image: psqldatabase
        entrypoint: /bin/bash
        networks:
            - core-application-network


networks:
    core-application-network:
        driver: bridge
